version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001" # 将容器的 5001 端口映射到主机的 5001 端口
    depends_on:
      - mongodb # 确保 MongoDB 在后端启动前运行
    environment:
      - MONGO_URI=mongodb://mongodb:27017/your_database_name # 后端连接 MongoDB 的 URI

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # 将容器的 80 端口映射到主机的 3000 端口

  mongodb:
    image: mongo:7.0 # 使用 MongoDB 官方镜像
    container_name: mongodb
    ports:
      - "27017:27017" # 将容器的 27017 端口映射到主机的 27017 端口
    volumes:
      - mongodb-data:/data/db # 持久化 MongoDB 数据

volumes:
  mongodb-data: # 定义一个持久化卷，用于存储 MongoDB 数据